# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0002_auto_20180219_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
