# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0003_carowner_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='phoneNumber',
        ),
    ]
