# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0009_auto_20180224_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='user',
            new_name='user1',
        ),
    ]
