# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 01:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0015_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='user',
            #field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            field=models.ForeignKey(default=b'10000000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),

        ),
    ]
