# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0027_auto_20180225_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pickuplocation',
            field=models.CharField(default=b'0', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='priceperhour',
            field=models.IntegerField(default=b'0'),
        ),
    ]
