# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0028_auto_20180226_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pickuplocation',
            field=models.CharField(default=b' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='priceperhour',
            field=models.IntegerField(default=b' '),
        ),
    ]
