# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0029_auto_20180227_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_pic',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
