# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0031_auto_20180227_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateTimeField(default=datetime.datetime(2018, 3, 21, 21, 43, 23, 19000))),
                ('drop_date', models.DateTimeField(default=datetime.datetime(2018, 3, 21, 21, 43, 23, 19000))),
            ],
        ),
    ]
