# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 21:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team6', '0032_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_id',
            field=models.CharField(default=b'cid', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 21, 48, 5, 351000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 21, 21, 48, 5, 351000)),
        ),
    ]
