# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 23:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0033_auto_20180321_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 21, 23, 41, 10, 971000)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 21, 23, 41, 10, 971000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 21, 23, 41, 10, 971000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 21, 23, 41, 10, 971000)),
        ),
    ]
