# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 00:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0037_auto_20180323_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='carid',
            field=models.ForeignKey(default=b'10000000000', on_delete=django.db.models.deletion.CASCADE, to='team6.Car'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 24, 0, 16, 28, 84000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 24, 0, 16, 28, 84000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 24, 0, 16, 28, 84000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 24, 0, 16, 28, 84000)),
        ),
    ]
