# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0039_auto_20180328_2242'),
        ('team6', '0040_auto_20180329_1108'),
    ]

    operations = [
    ]
