# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0041_merge_20180329_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 20, 4, 39, 179710)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 29, 20, 4, 39, 179753)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 20, 4, 39, 179563)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 29, 20, 4, 39, 179661)),
        ),
    ]
