# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0042_auto_20180329_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Reserved',
            field=models.CharField(default=b' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 21, 49, 33, 134898)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 29, 21, 49, 33, 134915)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 21, 49, 33, 134843)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 29, 21, 49, 33, 134875)),
        ),
    ]
