# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0044_auto_20180329_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Reserved',
            field=models.CharField(default=b'Not Reserved', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 22, 37, 5, 692664)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 29, 22, 37, 5, 692681)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 22, 37, 5, 692610)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 29, 22, 37, 5, 692641)),
        ),
    ]
