# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0045_auto_20180329_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Reserved',
            field=models.CharField(default=b'No', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 22, 59, 50, 95920)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 29, 22, 59, 50, 95940)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 3, 29, 22, 59, 50, 95865)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 3, 29, 22, 59, 50, 95898)),
        ),
    ]
