# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0046_auto_20180329_2259'),
        ('team6', '0042_auto_20180329_2004'),
    ]

    operations = [
    ]
