# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0047_merge_20180329_2335'),
        ('team6', '0041_merge_20180329_1512'),
    ]

    operations = [
    ]
