# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0048_auto_20180413_1952'),
        ('team6', '0050_auto_20180413_1951'),
    ]

    operations = [
    ]
