# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0048_auto_20180413_1952'),
        ('team6', '0049_auto_20180413_1615'),
        ('team6', '0050_auto_20180413_1951'),
    ]

    operations = [
    ]
