# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0051_merge_20180413_2313'),
        ('team6', '0049_auto_20180413_1615'),
    ]

    operations = [
    ]
