# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-14 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0052_merge_20180414_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengerCapacity',
            field=models.IntegerField(default=b''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 20, 3, 37, 886052)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 14, 20, 3, 37, 886072)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 14, 20, 3, 37, 886003)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 14, 20, 3, 37, 886033)),
        ),
    ]
