# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0053_auto_20180414_2003'),
        ('team6', '0051_merge_20180414_1623'),
    ]

    operations = [
    ]
