# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0056_auto_20180416_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.AddField(
            model_name='reg',
            name='location',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 16, 21, 51, 55, 813460)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 16, 21, 51, 55, 813480)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 16, 21, 51, 55, 813407)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 16, 21, 51, 55, 813437)),
        ),
    ]
