# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0055_auto_20180415_2006'),
        ('team6', '0056_auto_20180415_2013'),
    ]

    operations = [
    ]
