# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0057_auto_20180416_2151'),
        ('team6', '0057_merge_20180415_2352'),
    ]

    operations = [
    ]
