# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0058_merge_20180428_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=b'2018-04-28 22:05:00.258987'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 28, 22, 5, 0, 259011)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 22, 5, 0, 258934)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 28, 22, 5, 0, 258964)),
        ),
    ]
