# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0059_auto_20180417_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('role', models.CharField(default=b'admin', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('status', models.CharField(default=b'', max_length=200)),
                ('location', models.CharField(blank=True, default=b'', max_length=100)),
                ('role', models.CharField(default=b'customer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('status', models.CharField(default=b'', max_length=200)),
                ('role', models.CharField(default=b'owner', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 21, 7, 35, 601000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 28, 21, 7, 35, 601000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 28, 21, 7, 35, 601000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 28, 21, 7, 35, 601000)),
        ),
    ]
