# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0060_auto_20180428_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarOwner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=b'', editable=False, on_delete=django.db.models.deletion.CASCADE, to='team6.Reg_Owner'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 29, 19, 58, 44, 239000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 29, 19, 58, 44, 239000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 29, 19, 58, 44, 239000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 29, 19, 58, 44, 239000)),
        ),
    ]
