# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0061_auto_20180429_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='team6.Reg_Owner'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 29, 20, 13, 4, 907000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 29, 20, 13, 4, 907000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 29, 20, 13, 4, 907000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 29, 20, 13, 4, 907000)),
        ),
    ]
