# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0059_auto_20180428_2205'),
        ('team6', '0063_auto_20180429_1622'),
    ]

    operations = [
    ]
