# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 23:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0064_merge_20180429_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.BooleanField(default=True)),
                ('message', models.CharField(default=b'', max_length=250)),
                ('rating', models.IntegerField(default=1)),
                ('time', models.DateField(default=datetime.datetime(2018, 4, 29, 23, 40, 25, 777000))),
            ],
        ),
        migrations.AddField(
            model_name='reg_customer',
            name='num_feedbacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reg_customer',
            name='sum_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reg_owner',
            name='num_feedbacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reg_owner',
            name='sum_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=b'2018-04-29 23:40:25.777000'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 29, 23, 40, 25, 777000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 29, 23, 40, 25, 777000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 4, 29, 23, 40, 25, 777000)),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='team6.Reg_Customer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='owner',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='team6.Reg_Owner'),
        ),
    ]
