# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0064_merge_20180429_2105'),
        ('team6', '0065_auto_20180429_1940'),
    ]

    operations = [
    ]
