# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 00:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0066_merge_20180430_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_customer',
            name='latitude',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='reg_customer',
            name='longitude',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateField(default=datetime.datetime(2018, 5, 1, 0, 14, 25, 706000)),
        ),
        migrations.AlterField(
            model_name='reg_customer',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=b'2018-05-01 00:14:25.705000'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 5, 1, 0, 14, 25, 705000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 1, 0, 14, 25, 705000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 5, 1, 0, 14, 25, 705000)),
        ),
    ]
