# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0066_merge_20180501_0006'),
        ('team6', '0067_auto_20180430_2014'),
    ]

    operations = [
    ]
