# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team6', '0069_auto_20180505_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.DateField(default=datetime.datetime(2018, 5, 6, 23, 23, 7, 240000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_date',
            field=models.DateField(default=b'2018-05-06 23:23:07.240000'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='drop_time',
            field=models.TimeField(default=datetime.datetime(2018, 5, 6, 23, 23, 7, 240000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 6, 23, 23, 7, 240000)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_time',
            field=models.TimeField(default=datetime.datetime(2018, 5, 6, 23, 23, 7, 240000)),
        ),
    ]
